
[functions.delete-account]
enabled = true
verify_jwt = false
import_map = "./functions/delete-account/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/delete-account/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/delete-account/*.html" ]

[functions.loops-signup]
enabled = true
verify_jwt = false
import_map = "./functions/loops-signup/deno.json"
entrypoint = "./functions/loops-signup/index.ts"

[functions.loops-progress]
enabled = true
verify_jwt = false
import_map = "./functions/loops-progress/deno.json"
entrypoint = "./functions/loops-progress/index.ts"

[functions.backfill-loops-progress]
enabled = true
verify_jwt = false
import_map = "./functions/backfill-loops-progress/deno.json"
entrypoint = "./functions/backfill-loops-progress/index.ts"
